var courses = [{
        image: "template/images/javascriptDef.png",
        title: "what is javascript?",
        category: "JS",
        price: '9.9$',
    },
    {
        image: "template/images/htmlBasics.PNG",
        title: "basics of HTML",
        category: "HTML",
        price: '5.9$',
    },
    {
        image: "template/images/htmlElements.png",
        title: "HTML elements and tags",
        category: "HTML",
        price: '9.9$',
    },
    {
        image: "template/images/cssSelectors.jpg",
        title: "CSS selectors",
        category: "CSS",
        price: '69.9$',
    },
    {
        image: "template/images/javascriptVariables.png",
        title: "variables and data type of javascript",
        category: "JS",
        price: '19.9$',
    },
    {
        image: "template/images/javascriptOperators.png",
        title: "Javascript operators and conditions",
        category: "JS",
        price: '29.9$',
    },
    {
        image: "template/images/htmlAttrVal.jpg",
        title: "HTML attributes and values",
        category: "HTML",
        price: '19.9$',
    },
    {
        image: "template/images/cssProperties.png",
        title: "CSS properties",
        category: "CSS",
        price: '29.9$',
    },
    {
        image: "template/images/javascriptObjects.png",
        title: "Javascript objects and arrays",
        category: "JS",
        price: '39.9$',
    },
    {
        image: "template/images/cssMesures.png",
        title: "mesures and unites of CSS",
        category: "CSS",
        price: '19.9$',
    },
    {
        image: "template/images/cssAnimation.png",
        title: "CSS animations",
        category: "CSS",
        price: '19.9$',
    },
    {
        image: "template/images/javascriptFunctions.png",
        title: "The basics of javascript",
        category: "JS",
        price: '29.9$',
    },
    {
        image: "template/images/javascriptEvents.png",
        title: "javascript events",
        category: "JS",
        price: '59.9$',
    },
    {
        image: "template/images/cssColors.png",
        title: "css colors",
        category: "css",
        price: '29.9$',
    },
    {
        image: "template/images/phpBasics.png",
        title: "getting started with php",
        category: "php",
        price: '15.9$',
    },
    {
        image: "template/images/javascriptFunctions2.png",
        title: "functions and loops with javascript",
        category: "JS",
        price: '19.9$',
    },
    {
        image: "template/images/phpDataBase.png",
        title: "connecting to database using PHP",
        category: "PHP",
        price: '29.9$',
    },
    {
        image: "template/images/phpCRUD.png",
        title: "manipulating crud using php",
        category: "php",
        price: '45.9$',
    },
    {
        image: "template/images/javascriptDOM.png",
        title: "DOM the power of javascript",
        category: "JS",
        price: '23.9$',
    },
];